package:
  name: unit_conversion
  version: 2.2

# no source -- source is local

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
  home: https://github.com/NOAA-ORR-ERD/PyNUCOS
  license: Public Domain
  summary: 'Physical Unit conversions for Oil Spill Response'

